name: Auto PR via main

on:
  push:
    branches:
      - 'hotfix/**'
      - 'bug/**'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create PR using GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEST_BRANCH: "test"
          ASSIGNEE_USER: "peterpaularetex-creator" 
          REVIEWER_1: "peterpaularetex-creator"
          REVIEWER_2: "Aaron-anime"
        run: |
        
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          
          if [[ "$BRANCH_NAME" == bug/* ]]; then
            PR_LABEL="bug"
          elif [[ "$BRANCH_NAME" == hotfix/* ]]; then
            PR_LABEL="hotfix"
          elif [[ "$BRANCH_NAME" == enhancement/* ]]; then
            PR_LABEL="enhancement"
          elif [[ "$BRANCH_NAME" == duplicate/* ]]; then
            PR_LABEL="duplicate"
          else
            PR_LABEL="documentation" 
          fi
          
          gh pr create \
            --title "Automated PR: $BRANCH_NAME" \
            --body "This PR was automatically generated for branch $BRANCH_NAME." \
            --base "$TEST_BRANCH" \
            --head "$BRANCH_NAME" \
            --label "$PR_LABEL" \
            --reviewer "$REVIEWER_1, $REVIEWER_2" \
            --assignee "$ASSIGNEE_USER"